#!/bin/bash
source ~/.config/.sgpt

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    -m|--model)
      MODEL="$2"
      shift
      shift
      ;;
    -t|--temperature)
      TEMPERATURE="$2"
      shift
      shift
      ;;
    -m|--max-tokens)
      MAX_TOKEN="$2"
      shift
      shift
      ;;
    -b|--bearer)
      BEARER="$2"
      shift
      shift
      ;;
    -p|--prompt)
      PROMPT="$2"
      shift
      shift
      ;;
    *)
      PROMPT="$1" # go prompt by default
      shift
      ;;
  esac
done

if [ -z "$PROMPT" ]
then
      echo "prompt required"
      exit 1
fi

if [ -z "$TEMPERATURE" ]
then
      echo "temperature required"
      exit 1
fi

if [ -z "$MAX_TOKEN" ]
then
      echo "max-token required"
      exit 1
fi

if [ -z "$MODEL" ]
then
      echo "model required"
      exit 1
fi

if [ -z "$BEARER" ]
then
      echo "bearer required"
      exit 1
fi

curl=`cat <<EOS
curl https://api.openai.com/v1/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $BEARER" \
  -d '{
    "model": "$MODEL",
    "prompt": "$PROMPT",
    "max_tokens": $MAX_TOKEN,
    "temperature": $TEMPERATURE 
  }' 2>/tmp/sgpt | jq '.choices[]'.text | cut -c 6-
EOS`

result=`eval ${curl}`

exit_code=$?

if [ $exit_code -ne 0 ]; then
    cat /tmp/sgpt
    exit $exit_code
else
    echo -e $result | sed '$ s/.$//'
    echo $result | sed '$ s/.$//' | xclip -selection clipboard
fi
exit 0
